version: '3.1'

services:
  usuarios:
    image: elianfragozo/usuarios:v2
    hostname: usuarios
    ports:
     - "7127:80"
    networks:
      - proyecto
    environment:
      - USER_SERVICE_URL=http://usuarios:80/api/Users

  pacientes:
     image: elianfragozo/pacientes:v2
     hostname: pacientes
     ports:
      - "80:80"
     networks:
      - proyecto
     depends_on:
       - usuarios
     environment:
      - USER_SERVICE_URL=http://usuarios:80/api/Users

  citas:
     image: elianfragozo/proyectocitas:v1
     hostname: citas
     ports:
      - "81:80"
     networks:
      - proyecto

  horarios:
     image: elianfragozo/proyectohorarios:v1
     hostname: horarios
     ports:
      - "82:80"
     networks:
      - proyecto

  historias:
     image: elianfragozo/proyectohistorias:v1
     hostname: historias
     ports:
      - "83:80"
     networks:
      - proyecto

      
networks:
  proyecto:
    driver: bridge