version: '3.7'

services:
  
  usuarios:
    image: elianfragozo/usuarios:v2
    hostname: usuarios
    ports:
     - "81:80"
    networks:
      - proyecto

  citas:
     image: elianfragozo/proyectocitas:v1
     hostname: citas
     ports:
      - "82:80"
     networks:
      - proyecto

  horarios:
     image: elianfragozo/proyectohorarios:v1
     hostname: horarios
     ports:
      - "83:80"
     networks:
      - proyecto

  historias:
     image: elianfragozo/proyectohistorias:v1
     hostname: historias
     ports:
      - "84:80"
     networks:
      - proyecto

      
networks:
  proyecto:
    driver: bridge